###
DELETE http://localhost:8000/products/094bfb5e-1bed-401d-a496-8936c9291d05
Accept: application/json


###
GET http://localhost:8000/products/f8c2914d-ddc9-4467-8268-69bf3bd8447d
Accept: application/json

###
GET http://localhost:8000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njc2MDY1MTcsInN1YiI6IjkyOTFmYjE2LTQ2NjctNDljMC05YmNlLTNjNmRhNzcwZDMwMCJ9.mM35K0TMXqWrdIHnlQGY_SQWgPopx9rmenoj1cbbFGU
Accept: application/json


###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}

###

PUT http://localhost:8000/products/f8c2914d-ddc9-4467-8268-69bf3bd8447d
Content-Type: application/json

{
  "name": "My Product Updated",
  "price": 300
}

###
