POST http://localhost:8000/users/generate_token
Content-Type: application/json

{
    "email": "mail@mail.com",
    "password": "123456"
}

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "mail@mail.com",
    "password": "123456"
}

###
